### ISSUE TITLE
Button hard delay after playing 6/10 minutes in-game 

### ISSUE THREAD

**Issue by kodiakhub** [djlastnight/KeyboardSplitterXbox#23]
Hello! We are playing FIFA 19 with 2 keyboard. So first match was very well, but the delay after the second match begins to appear very heavily. The next time we restart the game, there's the same situation. Is there a solution to this? Thank you!

**Comment by djlastnight** [comment]
Hi. I never heard for this kind of issues. It will be very hard to fix this. Can you post your PC full specs.

**Comment by kodiak09** [comment]
Her you go! We're restart the FIFA 19 game every after the first match is over. Because if we do keep playing after 1st match then something about the button delays will be like leak/lag/bug.

Specs:

Operating System: Windows 10 Pro 64-bit (10.0 Build 18362)
Motherboard: Gigabyte-A320M-DS2
CPU: AMD Ryzen 3 1300X Quad-Core
GPU: NVIDIA GeForce GTX 1050 Ti
Memory: 8GB
SSD: JAMESDONKEY JD240 240GB
Keyboard: Logitech G103 (2 keyboard)

**Comment by djlastnight** [comment]
Can you please enable the 'Ultimate performance' power plan from your Windows settings. Reboot your PC and try again to play FIFA. Thank you.

**Comment by kodiak09** [comment]
Hi, yes we tried everything as possible like disable blockchain and mouse and applied to 2 keyboards didnt not as same as buttons key available and still there is delay goes after playing a bit time. So i think its hard to find what cause to this problem. Actually it's not like delay, its like when you to press run and shoot then its applied after 2 seconds or any key does not working within on 2 seconds. This is not always continious, which means that the is like load is loaded once every 5-10 seconds then that delay happens. Have fun!

**Comment by Onset** [comment]
Same here. Overcooked game unplayable after a minute.

![image](https://user-images.githubusercontent.com/1045362/71484741-4590eb80-280e-11ea-8c72-0354fcd2fbe2.png)

**Comment by djlastnight** [comment]
Its normal, while the input monitor is open.
