### ISSUE TITLE
keyboard splitter is not opening  i had download the version 2.0.0.3 and verdist x86  but not opening please comment fast 

### ISSUE THREAD

**Issue by aadi0305** [djlastnight/KeyboardSplitterXbox#24]

**Comment by djlastnight** [comment]
Please download the newest and attach the log fast

**Comment by hemantkolate** [comment]
Hi, Same thing happening, did everything as mentioned still the app is not opening. Everytime it asks to install the drivers and start the application again. 


[Fri] 27 Nov, 2020 [09:48:48] [Mem: 25 MB] - Application started from C:\Users\Hemant Kolate\Downloads\Keyboard.Splitter.2.2.0.0\KeyboardSplitter.exe
[Fri] 27 Nov, 2020 [09:48:48] [Mem: 25 MB] - User has write permissions: True
[Fri] 27 Nov, 2020 [09:48:48] [Mem: 25 MB] - Application version: djlastnight's Gaming Keyboard Splitter v2.2.0.0
[Fri] 27 Nov, 2020 [09:48:48] [Mem: 25 MB] - OS version: Windows 10 x64 build 18362 
[Fri] 27 Nov, 2020 [09:48:48] [Mem: 25 MB] - Setting environment
[Fri] 27 Nov, 2020 [09:48:48] [Mem: 26 MB] - Loading interception 1.00
[Fri] 27 Nov, 2020 [09:48:48] [Mem: 26 MB] - Loading VirtualXboxNative 2.2.0.0
[Fri] 27 Nov, 2020 [09:48:48] [Mem: 33 MB] - Loading SplitterCore 2.2.0.0
[Fri] 27 Nov, 2020 [09:48:48] [Mem: 33 MB] - Loading Interceptor 2.2.0.0
[Fri] 27 Nov, 2020 [09:48:49] [Mem: 33 MB] - Loading VirtualXbox 2.2.0.0
[Fri] 27 Nov, 2020 [09:48:49] [Mem: 34 MB] - Interception driver state: installed
[Fri] 27 Nov, 2020 [09:48:49] [Mem: 34 MB] - ScpVBus driver state: not installed
[Fri] 27 Nov, 2020 [09:48:49] [Mem: 34 MB] - Xbox accessories driver state: installed
[Fri] 27 Nov, 2020 [09:48:49] [Mem: 34 MB] - Built-in drivers are not installed, asking user to install them
[Fri] 27 Nov, 2020 [09:48:53] [Mem: 51 MB] - Skipping interception driver installation, because it is already installed
[Fri] 27 Nov, 2020 [09:48:53] [Mem: 51 MB] - Installing virtual xbox bus (SCP) driver
[Fri] 27 Nov, 2020 [09:49:00] [Mem: 54 MB] - Output from ScpVBus installtion: Device node created. Install is complete when drivers are installed...
Updating drivers for Root\ScpVBus from C:\Users\Hemant Kolate\AppData\Local\Temp\VirtualXbox 2.2.0.0 resources\ScpVBus.inf.

[Fri] 27 Nov, 2020 [09:49:01] [Mem: 54 MB] - Application exited with code: 0
