### ISSUE TITLE
Run it from command line?

### ISSUE THREAD

**Issue by EduardoMaia** [djlastnight/KeyboardSplitterXbox#32]
Hi, thanks for this amazing work.
Is there a way to run it from a command line, such a Batch file with no need to interaction with the KeyboardSplitterXbox windows?
I want to run this everytime i run a game and want to close it if the game is closed.

**Comment by djlastnight** [comment]
Currently this is not possible.
I was thinking about this a long time ago.

I have to implement it.

The idea is to use only the core funtionality and to detach the GUI, but not completely.
The GUI will be used to install the drivers and to create custom presets and pre-configured game presets.

Once you have the presets and drivers you may run it from cmd, using command like this
`keyboard_splitter.exe default fifa`
which will create 2 virtual gamepads
1st mapped to default preset
2nd mapped to fifa preset

to stop the app, use command like this
`keyboard_splitter.exe -exit`

Due to I already created game presets/settings, which saves the slots information and runs the
desired game, I may also add command to run the game directly (this is saved to games xml).
So the command may be similar to this
`keyboard_splitter.exe -run fifa`
This will start the emulation with the slot settings sets at games xml for a game called 'fifa'.
It will also run the game if you set this in the settings (I made this optional, because some games does not like to be run from another apps).

Due to everything is currently tied to the GUI I have to change the source code.
You know this takes time. Unfortunately I am very busy, but I will see what can I do.

I repeat - this is an idea and it is currently not available.
Let me know what you think about it.

**Comment by EduardoMaia** [comment]
Your idea is brilliant and that's exactly what I was thinking!
 I have an arcade machine and I use a keyboard-based joystick, and games like Dead or Alive 6 or Jump Force, only can be played with xbox controller. When I first discovered your software, this was the perfect solution to my problems, but having to open the program every time I select a game is very annoying.
I understand that you don't have much time to implement this right now. 
There are more important priorities in life, like real work to pay bills, spend time with friends/family.
I feel bad that I don't know anything about programming and being able to help you.
If there is any way that I can help you speed up the process, such as donation, let me know.
Thanks a lot for the atention and sorry ir my english is not good.

**Comment by EduardoMaia** [comment]
Sorry for revive this thread. Did you think about it?

**Comment by Mwhtie22** [comment]
This tool is great so far! I also would love to have something to just start the emulation. like --start, to start the emulation process. This is so far the only tool that works well for my arcade cabinet setup. Really hope this get's implemented.

**Comment by ctindell81** [comment]
@djlastnight I would love to see what I can do as far as implementing command line parameters. I am not gonna lie though...I have ZERO experience in editing source code, creating my own program etc. I am just finally at the point of being comfortable enough to start considering creating my own programs. I recently installed visual basic to create another program that I ended up using AHK for. Still, I would love to contribute. If someone with more experienced hands would like to kind of explain the absolute basics in using and editing source code...this would be of great help.

**Comment by pragunvohra** [comment]
AutoHotKey script that makes it work for two players. Compile it to ahk and in windows, run the .exe as admin and then run the game once the exe ends execution (i.e. you can put it sequentially in a batch file). This is hardcoded for 2p but that's all I needed. Make sure you turn off UAC on the machine so you don't get popups when the game tries to run.

This is hardcoded to use keyboard_01...just change it if you need it.
Put in the same folder as KeyboardSplitter.exe.
Usage: runWithSettings.ahk <Profile1> <Profile2>
e.g.:
runWithSettings ipac1 ipac2
runWithSettings ipacdpad1 ipacdpad2

If it doesn't work, try adding some sleeps. The below runs fine for me, but if you have an older computer you may need some sleeps and also change the SetKeyDelay to something other than 0. It takes ~1 second to run this. I am using version 2.2.0.0. YMMV with other versions.

Hope it helps

AHK Script:
`; Defaults
Profile1 = ipac1
Profile2 = ipac2

; Get profiles from params
var1 = %1%
var2 = %2%
If var1 != ""
 Profile1 = %var1%
If var2 != ""
 Profile2 = %var2%

; Do your thing
SetKeyDelay, 0
Process, Close, KeyboardSplitter.exe
Sleep, 10
Run KeyboardSplitter.exe
SetTitleMatchMode, 2
WinWait djlastnight
WinRestore
WinActivate
WinGetPos X, Y, W, H
while (W < 750) {
 WinGetPos X, Y, W, H
 Sleep, 10
}

Send {Tab 8}
Send 2
Send {Tab 5}
Send Keyboard_01
Send {Tab 2}
Send N
Send {Tab 2}
Send %Profile1%
Send {Tab 58}
Send Keyboard_01
Send {Tab 2}
Send N
Send {Tab 2}
Send %Profile2%
Send {Tab 69}
Sleep, 200
Send {Enter}
WinMinimize`

**Comment by eckers569** [comment]
I recently stumbled across this great app when trying to get KOF XV running on my arcade cab via IPAC encoder.

I was having trouble with the AHK script above. I'm not great with this sort of thing but managed to get it working and it may help others if also having the same issues that I was with the AHK script above - which I'm certain is user error on my part.

First of all make sure you run the script as administrator or won't work (not sure how I missed this in the instructions provided :-))

In any-case, I still found that the relevant UI boxes weren't completing automatically for me. It didn't appear to make much difference if I ran as straight AHK or compiled to EXE or how much I amended timings or added additional sleeps etc.

I couldn't get the profiles to load, so amended the script to key them separately (in my case 'Arcade1' and 'Arcade2'), but still (or more likely because of this) had issues with the rest of it updating the UI correctly...

I slowed the key entries in the code right down to determine what was going on and found that an extra box was appearing after the profile was selected (to delete and/or save) which was different to when i manually select my profiles (where only 'delete' is present). This put the number of 'tabs' out in the above script, meaning the rest of the script from that point on would fail to update the correct UI elements and ultimately start the controller emulation.

I'm sure I'm still doing something wrong with the first bit about the profiles etc which caused my issue, but I changed the above script to work around this until i understand it better.

This is the slowed down version so I could see what was going on and needs to speed back up again;

I've also shorted some of the UI entries for the keyboard. Again, I too only wanted 1 keyboard for 2 controllers and found just sending 'k' selected keyboard_01 for both profiles.


; Defaults ----- I couldn't get this to work so set to key my profiles individually below
Profile1 = Arcade1
Profile2 = Arcade2

; Get profiles from params ----- I couldn't get this to work so set to key my profiles individually below
var1 = %1%
var2 = %2%
If var1 != ""
 Profile1 = %var1%
If var2 != ""
 Profile2 = %var2%

; Wait for the window to be loaded and active
SetKeyDelay, 1000   ;set this back to default 0 or at least much faster, this will just help you see the UI being updated by this script>>>>
Process, Close, KeyboardSplitter.exe
Sleep, 10
Run KeyboardSplitter.exe
SetTitleMatchMode, 2
WinWait djlastnight
WinRestore
WinActivate
WinGetPos X, Y, W, H
while (W < 750) {
 WinGetPos X, Y, W, H
 Sleep, 10
}

; Send tabs and various keys...
Send {Tab 8}
; 2 for 2 players
Send 2
Send {Tab 5}
; Keyboard_01 for player 1
Send K
Send {Tab 2}
; N for N/A for mouse
Send N
Send {Tab 2}
; Profile specified in command line for p1
Send Arcade1
Send {Tab 59}
; Keyboard_01 for player 2
Send K
Send {Tab 2}
; N for N/A for mouse
Send N
Send {Tab 2}
; Profile specified in command line for p2
Send Arcade2
Send {Tab 70}
; May need a longer delay than 200ms if your computer is slow ---- again speed back up to default 200 once you happy
Sleep, 3000
Send {Enter}
; Minimize the app
WinMinimize

**Comment by eckers569** [comment]
oh - and don't have this webpage open or anything else with 'djlastnight' in the title when you run the script or the key entries can register on that instead of the app UI!

**Comment by mxfwdspd** [comment]
> oh - and don't have this webpage open or anything else with 'djlastnight' in the title when you run the script or the key entries can register on that instead of the app UI!
> 
> And my IPAC encoder is recognised as 'Keyboard_02' so I had to change that in my amended script or my normal keyboard worked but my arcade buttons still didn't.
> 
> I've set up a script to auto-launch this in Launch Box with the relevant game - and that's why you need to compile it as an EXE (via the AutoHotKey apps) so you can specify it to always 'run as administrator' (which i don't think you can do with just AHK script automatically. Just need to amend another script to turn off Keyboardsplitter once KOF XV closes in my Launchbox/Bigbox 'additional apps' and job done - another weekend gone!

Thanks for the info in your post. Trying to do the same thing as you, using launchbox additional apps to start with a specific game. Usually I use the keyboard escape key in my other ahks to close the games, but how did you accomplish that since the keyboard keys become blocked?

**Comment by eckers569** [comment]
> > oh - and don't have this webpage open or anything else with 'djlastnight' in the title when you run the script or the key entries can register on that instead of the app UI!
> > And my IPAC encoder is recognised as 'Keyboard_02' so I had to change that in my amended script or my normal keyboard worked but my arcade buttons still didn't.
> > I've set up a script to auto-launch this in Launch Box with the relevant game - and that's why you need to compile it as an EXE (via the AutoHotKey apps) so you can specify it to always 'run as administrator' (which i don't think you can do with just AHK script automatically. Just need to amend another script to turn off Keyboardsplitter once KOF XV closes in my Launchbox/Bigbox 'additional apps' and job done - another weekend gone!
> 
> Thanks for the info in your post. Trying to do the same thing as you, using launchbox additional apps to start with a specific game. Usually I use the keyboard escape key in my other ahks to close the games, but how did you accomplish that since the keyboard keys become blocked?

Chiming in to add that i found this so useful - for KOF and also WWE Allstars via RPCS3 (where using keyboard, IPAC and/or every combination with any other xinput encoder software kept causing conflicts with my P1 and P2 direction controls, but fine in every other PS3 game); KBSplitter was this only thing that worked for this titles, but i couldnt automate the profiles/presets needed until i saw this thread.

Thank you - your efforts greatly appreciated.

One issue i did have - which took me hours to figure out - when i changed my monitor to an older CRT, this script no longer worked (launched the app but wouldn't run through the tabs and keystrokes). It was to do with this part of the script:

WinGetPos X, Y, W, H
while (W < 750) {
WinGetPos X, Y, W, H
Sleep, 10

However it would work as it intended once i'd manually force KBSplitter in to fullscreen. 

By changing to:

WinGetPos X, Y, W, H
while (W < 590) {
WinGetPos X, Y, W, H
Sleep, 10

it worked again in windowed mode.

My current resolution for monitor in DIY Arcade is 1024 x 768, so assume the script above is saying ignore widow width less than 750 hence it didn't run through the keystrokes until i went full screen. Changing to <590 with this non-standard resolution did the trick.

Unlikely many others will have this issue - but i'll probably forget the next time i switch out monitors so worth a footnote.
