### ISSUE TITLE
Mouse and Keyboard Issue

### ISSUE THREAD

**Issue by Rettend** [djlastnight/KeyboardSplitterXbox#34]
This program is really helpful for me, thanks! I can now play with my friends locally.

My issue is when the program is running (without pressing Start) my typing and scrolling gets really laggy (inside any game, in the browser and everywhere), but only during the prog's run. Not a huge problem but It can be fixed.

I think the installed driver messes up something.

Thanks!

**Question 2: I see the program requires admin permissions, does it need administrator perms anyway?**

**Comment by djlastnight** [comment]
Hi there. Thanks for the good words.
A1: This is really strange, because the app just reads the input and pass it directly to windows, while the emulation is stopped. I know that expanding the input monitor causes additional delay. The last time I made delay tests the results was as similar to this: ~100ms for the first hit, a few ms for any further.

A2: Actually, once you have the drivers installed, if I remember well, there is no need to run the app as admin. It is just easier for me to always require admin perms.

Can you please try to re-install the interception driver?
https://github.com/djlastnight/KeyboardSplitterXbox/blob/master/InterceptionUninstall/interception-gui-uninstaller.zip?raw=true
Sometimes windows updates are causing issues to the upper keyboard drivers.
Hope this helps.

**Comment by itsmemandeep** [comment]
i am a regular user of this but once my keyboard started to not work in my computer and after fixing that problem when i use keyboard splitter my mouse input is working but my keyboard doesnt shows up.IT works in other application as usual but not in keyboard splitter in the option of choosing the keyboard there is none i searched and tried everything hep me!
